const SampleBooks = () => {
  const booksInfo = [
    {
      title: "Science Fiction",
      image:
        "https://raw.githubusercontent.com/adarshagupta/trybookai/main/public-assets/paradox.png",
      description:
        "As Dr. Elara stepped through the shimmering portal, she knew there was no turning back. The fate of two universes now rested in her hands...",
    },
    {
      title: "Mystery",
      image:
        "https://raw.githubusercontent.com/adarshagupta/trybookai/main/public-assets/mist.png",
      description:
        "The old lighthouse stood silent, its beacon long extinguished. But on foggy nights, some swore they could still see its ghostly light...",
    },
    {
      title: "Fantasy",
      image:
        "https://raw.githubusercontent.com/adarshagupta/trybookai/main/public-assets/ecos.png",
      description:
        "The ancient prophecy spoke of a child born with starlight in their eyes. As the comet blazed overhead, the kingdom held its breath...",
    },
  ];
  return (
    <section className="mt-20" aria-labelledby="books-section-heading">
      <div className="text-center">
        <h2 id="books-section-heading" className="font-bold text-2xl mb-6">
          Sample Books Generated by BookAI
        </h2>
        <p className="text-lg" id="books-section-description">
          Explore some of the captivating books created using our AI technology.
        </p>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mt-10">
        {booksInfo.map((item, idx) => (
          <div
            key={idx}
            className="px-6 lg:px-8 py-6 bg-[#ffffff0d] rounded-md text-center space-y-3 cursor-pointer transition duration-300 hover:-translate-y-2"
            role="article"
            aria-labelledby={`book-title-${idx}`}
            aria-describedby={`book-description-${idx}`}
          >
            <img
              className="h-[300px] w-[200px] mx-auto rounded-md"
              src={item.image}
              alt={item.title}
              aria-hidden="true"
            />
            <h3 id={`book-title-${idx}`} className="text-xl font-bold pt-4">
              {item.title}
            </h3>
            <p
              id={`book-description-${idx}`}
              className="italic text-[#b3b3b3] md:h-[120px]"
            >
              {`"${item.description}"`}
            </p>
            <a
              className="cursor-pointer text-[#8a2be2] font-light transition-colors duration-300 ease-linear hover:text-[#fff]"
              href="#"
              aria-label={`Read more about ${item.title}`}
            >
              Read More
            </a>
          </div>
        ))}
      </div>
    </section>
  );
};

export default SampleBooks;
